included:
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - Generated

opt_in_rules:
  - empty_count
  - force_unwrapping
  - unowned_variable_capture
  - array_init
  - yoda_condition
  - attributes
  - explicit_init
  - sorted_imports
  - trailing_closure
  - redundant_nil_coalescing
  - file_types_order
  - closure_end_indentation

disabled_rules:
  - line_length
  - identifier_name
  - type_name

reporter: xcode

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 40
  error: 80

type_body_length:
  warning: 200
  error: 400

file_length:
  warning: 400
  error: 800

identifier_name:
  excluded:
    - id
    - x
    - y
    - i
    - j
